### ISSUE TITLE
Verify that pip installed package works

### ISSUE THREAD

**Issue by d-meiser** [d-meiser/cold-atoms#54]

**Comment by d-meiser** [comment]
Install seems to work but I get a bunch of scary looking error messages:

```
(env) (513) scratch ] pip install coldatoms
Collecting coldatoms
  Downloading coldatoms-0.1.11.tar.gz (93kB)
    100% |████████████████████████████████| 102kB 801kB/s
Collecting cython (from coldatoms)
  Using cached Cython-0.27.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting numpy (from coldatoms)
  Using cached numpy-1.13.3-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Building wheels for collected packages: coldatoms
  Running setup.py bdist_wheel for coldatoms ... error
  Complete output from command /Users/dmeiser/Documents/scratch/env/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/4s/klw69tnn6jv3nzzyb9tpr5pcl6_ghs/T/pip-build-1RU17_/coldatoms/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/4s/klw69tnn6jv3nzzyb9tpr5pcl6_ghs/T/tmpaCfj4mpip-wheel- --python-tag cp27:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/4s/klw69tnn6jv3nzzyb9tpr5pcl6_ghs/T/pip-build-1RU17_/coldatoms/setup.py", line 117, in <module>
      setup_package()
    File "/private/var/folders/4s/klw69tnn6jv3nzzyb9tpr5pcl6_ghs/T/pip-build-1RU17_/coldatoms/setup.py", line 112, in setup_package
      metadata.update(get_package_info())
    File "/private/var/folders/4s/klw69tnn6jv3nzzyb9tpr5pcl6_ghs/T/pip-build-1RU17_/coldatoms/setup.py", line 32, in get_package_info
      from Cython.Build import cythonize
  ImportError: No module named Cython.Build

  ----------------------------------------
  Failed building wheel for coldatoms
  Running setup.py clean for coldatoms
  Complete output from command /Users/dmeiser/Documents/scratch/env/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/4s/klw69tnn6jv3nzzyb9tpr5pcl6_ghs/T/pip-build-1RU17_/coldatoms/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/4s/klw69tnn6jv3nzzyb9tpr5pcl6_ghs/T/pip-build-1RU17_/coldatoms/setup.py", line 117, in <module>
      setup_package()
    File "/private/var/folders/4s/klw69tnn6jv3nzzyb9tpr5pcl6_ghs/T/pip-build-1RU17_/coldatoms/setup.py", line 112, in setup_package
      metadata.update(get_package_info())
    File "/private/var/folders/4s/klw69tnn6jv3nzzyb9tpr5pcl6_ghs/T/pip-build-1RU17_/coldatoms/setup.py", line 32, in get_package_info
      from Cython.Build import cythonize
  ImportError: No module named Cython.Build

  ----------------------------------------
  Failed cleaning build dir for coldatoms
Failed to build coldatoms
Installing collected packages: cython, numpy, coldatoms
  Running setup.py install for coldatoms ... done
Successfully installed coldatoms-0.1.11 cython-0.27.1 numpy-1.13.3
(env) (514) scratch ] python
Python 2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import coldatoms
>>> print(coldatoms.__version__)
0.1.11
```
